const evos = {
  grassStarter: {index: 0, evos: [{index: 1, evoType: "lvl 16", evos: [{index: 2, evoType: "lvl 36"}]}]},
  fireStarter: {index: 3, evos: [{index: 4, evoType: "lvl 16", evos: [{index: 5, evoType: "lvl 36"}]}]},
  waterStarter: {index: 6, evos: [{index: 7, evoType: "lvl 16", evos: [{index: 8, evoType: "lvl 36"}]}]},
  viceroy: {index: 9, evos: [{index: 10, evoType: "lvl 8", evos: [{index: 11, evoType: "lvl 12"}]}]},
  otters: {index: 15, evos: [{index: 16, evoType: "lvl 24"}, {index: 17, evoType: "water stone"}]},
  wildCharge: {index: 24, evos: [{index: 25, evoType: "lvl 33"}, {index: 26, evoType: "wild"}]},
  ghostCham: {index: 27, evos: [{index: 28, evoType: "lvl 28"}]},
  turnip: {index: 30, evos: [{index: 31, evoType: "lvl 22"}]},
  statue: {index: 36, evos: [{index: 37, evoType: "lvl 32"}]},
  fishlet: {index: 38, evos: [{index: 39, evoType: "???"}]},
  cockatrice: {index: 146, evos: [{index: 147, evoType: "lvl 30", evos: [{index: 148, evoType: "lvl 55"}]}]},
};

export default [
  {sprite: "001.gif", name: "Wabalea", category: "Meadow", type: ["Grass"], dex: "It lies on its stomach and absorbs sunlight.", height: "3’05”", weight: "25.1", evos: evos.grassStarter},
  {sprite: "002.gif", name: "Kwabalea", category: "Meadow", type: ["Grass"], evos: evos.grassStarter},
  {sprite: "003.gif", name: "Hyacolea", category: "Meadow", type: ["Grass"], evos: evos.grassStarter},
  {sprite: "004.gif", type: ["Fire"], category: "Spore", evos: evos.fireStarter},
  {sprite: "005.gif", type: ["Fire", "Ground"], category: "Spore", evos: evos.fireStarter},
  {sprite: "006.gif", type: ["Fire", "Ground"], category: "Spore", evos: evos.fireStarter},
  {sprite: "007.gif", type: ["Water", "Poison"], evos: evos.waterStarter},
  {sprite: "008.gif", type: ["Water"], evos: evos.waterStarter},
  {sprite: "009.gif", name: "Calawary", type: ["Water", "Fighting"], evos: evos.waterStarter},
  {sprite: "010.gif", type: ["Bug"], evos: evos.viceroy},
  {name: "Rhysli", evos: evos.viceroy},
  {evos: evos.viceroy},
  {},
  {},
  {},
  {sprite: "016.gif", type: ["Normal"], category: "Squirrel", evos: evos.otters},
  {sprite: "017.gif", type: ["Normal"], category: "River Otter", evos: evos.otters},
  {sprite: "018.gif", type: ["Normal", "Rock"], category: "Sea Otter", dex: "It spends most of its life in water. It uses its water stone to crack clams.", evos: evos.otters},
  {},
  {},
  {},
  {},
  {},
  {},
  {sprite: "wip-wildcharge1.gif", type: ["Electric"], evos: evos.wildCharge},
  {evos: evos.wildCharge},
  {sprite: "wip-tzzarwal.gif", name: "Tzzarwal", type: ["Electric"], evos: evos.wildCharge},
  {sprite: "wip-ghost-orb.gif", type: ["Ghost"], evos: evos.ghostCham},
  {sprite: "wip-ghost-chameleon.gif", type: ["Normal", "Ghost"], evos: evos.ghostCham},
  {sprite: "wip-snail.gif", type: ["Ice", "Poison"]},
  {sprite: "wip-turnip.gif", name: "Turnite", type: ["Grass"], category: "Turnip", height: "1’05”", weight: "0.6", evos: evos.turnip},
  {sprite: "wip-turnipbird.gif", name: "Tadaikon", type: ["Grass", "Flying"], category: "Turnip Bird", height: "3’02”", weight: "16.1", evos: evos.turnip},
  {type: ["Psychic"], category: "Foolish"},
  {type: ["Psychic", "Fire"], category: "Magician"},
  {type: ["Psychic", "Fire"], category: "Peafowl"},
  {sprite: "wip-slushie.gif", name: "Slugshie", category: "Litter", dex: "It occupies discarded trash as protection. It must transfer to larger vessels as it grows." },
  {sprite: "wip-anubis.gif", type: ["Rock"], category: "Statue", evos: evos.statue},
  {sprite: "wip-sphinx.gif", type: ["Rock"], category: "Statue", evos: evos.statue},
  {evos: evos.fishlet},
  {sprite: "wip-fishlet.gif", evos: evos.fishlet, type: ["Bug", "Water"]},
  {},
  {sprite: "vorpelos.gif", name: "Vorpelos", type: ["Normal"], category: "Hairy", height: "5’03”", weight: "168.0"},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {sprite: "147.gif", type: ["Dragon"], evos: evos.cockatrice},
  {sprite: "148.gif", type: ["Dragon"], evos: evos.cockatrice},
  {sprite: "149.gif", type: ["Dragon"], evos: evos.cockatrice},
  {},
];
