export default [
  {sprite: "001.gif", name: "Wabalea", category: "Meadow", type: ["Grass"]},
  {sprite: "002.gif", name: "Kwabalea", category: "Meadow", type: ["Grass"]},
  {sprite: "003.gif", name: "Hyacolea", category: "Meadow", type: ["Grass"]},
  {sprite: "004.gif", type: ["Fire"]},
  {sprite: "005.gif", type: ["Fire"]},
  {sprite: "006.gif", type: ["Fire", "Ground"]},
  {sprite: "007.gif", type: ["Water", "Poison"]},
  {sprite: "008.gif", type: ["Water"]},
  {sprite: "009.gif", name: "Calawary", type: ["Water", "Fighting"]},
  {},
  {},
  {},
  {},
  {},
  {},
  {sprite: "016.gif", type: ["Normal"], category: "Squirrel"},
  {sprite: "017.gif", type: ["Normal"], category: "River Otter"},
  {sprite: "018.gif", type: ["Normal", "Rock"], category: "Sea Otter", dex: "It spends most of its life in water. It uses its water stone to crack clams."},
  {},
  {},
  {},
  {},
  {},
  {},
  {sprite: "wip-wildcharge1.gif", type: ["Electric"]},
  {},
  {sprite: "wip-tzzarwal.gif", name: "Tzzarwal", type: ["Electric"]},
  {sprite: "wip-ghost-orb.gif", type: ["Ghost"]},
  {sprite: "wip-ghost-chameleon.gif", type: ["Normal", "Ghost"]},
  {sprite: "wip-snail.gif", type: ["Ice", "Poison"]},
  {sprite: "wip-turnip.gif", name: "Turnite", type: ["Grass"], category: "Turnip"},
  {sprite: "wip-turnipbird.gif",type: ["Grass", "Flying"], category: "TurnipBird"},
  {type: ["Psychic"], category: "Foolish"},
  {type: ["Psychic", "Fire"], category: "Magician"},
  {type: ["Psychic", "Fire"], category: "Peafowl"},
  {sprite: "wip-anubis.gif", type: ["Rock"]},
  {sprite: "wip-sphinx.gif", type: ["Rock"]},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {sprite: "147.gif", type: ["Dragon"]},
  {sprite: "148.gif", type: ["Dragon"]},
  {sprite: "149.gif", type: ["Dragon"]},
  {},
];
